name: lint-build-test

on: push

jobs:
    lint:
        strategy:
            matrix:
                version: ["1.20"]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.version }}
                # Cache is managed by golangci-lint
                # https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
                cache: false
            - uses: actions/checkout@v3
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                version: v1.29

    build-test:
        strategy:
            matrix:
                version: ["1.20", "stable"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.version }}
                cache: false
            - uses: actions/checkout@v3
            - name: Build
              run: go build -v ./...
            - name: Test
              run: go test -v ./...
